### PR TITLE
Update SettingsController.php for Nova 4.26.0

### PR DESCRIPTION
**Pull request by puzzledmonkey**
this fixes https://github.com/outl1ne/nova-settings/issues/166

### CODE REVIEW

**Comment by crynobone** [comment]
@puzzledmonkey should also bump `laravel/nova` to `^4.26`: https://github.com/outl1ne/nova-settings/blob/28924850d89893d5d9441de839ff2c1efb863dad/composer.json#L11

**Comment by puzzledmonkey** [comment]
> @puzzledmonkey should also bump `laravel/nova` to `^4.26`:
> 
> https://github.com/outl1ne/nova-settings/blob/28924850d89893d5d9441de839ff2c1efb863dad/composer.json#L11

@crynobone thanks, is this Fluent class only available from 4.26.0 onwards then?

**Comment by crynobone** [comment]
Yes, that's correct.

**Comment by puzzledmonkey** [comment]
> Yes, that's correct.

Thanks - bumped as suggested

**Comment by marttinnotta** [comment]
Hi and thank you for your contribution!

Will create a new release in a moment.

**Pull request merged**
